name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Checkout do repositório
      - uses: actions/checkout@v4

      # Passo 2: Roda a Action do GitHub Snake
      - uses: Platane/snk@v3
        with:
          github_user_name: PedroZxK
          # O arquivo de saída (saída do snake)
          outputs: dist/github-contribution-grid-snake.svg
        env:
          # Usa o token padrão de segurança do GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Passo 3: Faz o commit do SVG gerado para a branch 'output'
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          # Permite que a Action crie e faça commit na branch 'output'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
